### ISSUE TITLE
请问price.mat数据可以找到吗？

### ISSUE THREAD

**Issue by Gaby123456** [blackmount8/Generalized_MG#1]
由于看到您的论文 所以想试试代码能不能使用，但是好像差一个数据，请问在哪里可以找到这个数据呢？

**Comment by xiaoyuanweiisme** [comment]
me too

**Comment by juchengquan** [comment]
Some data files have been intentionally removed due to confidentiality agreements in corporation with other institutes. 

However, 'price.mat' can be extracted and simulated from EMCSG official website here: 
https://www.emcsg.com/MarketData/PriceInformation

As the prices used in the manuscript were USEP, you may add upper/lower buffers to simulate buying/selling prices.

**Comment by xiaoyuanweiisme** [comment]
thank you so much! sir



ju.chengquan ***@***.***> 于2022年7月20日周三 10:07写道：

**Comment by xiaoyuanweiisme** [comment]
sir，the document include which information？

yuan xiao ***@***.***> 于2022年7月24日周日 19:58写道：
