### ISSUE TITLE
How can I not find this file?‘price.mat’

### ISSUE THREAD

**Issue by xiaoyuanweiisme** [blackmount8/Generalized_MG#2]
How can I not find this file?‘price.mat’

**Comment by juchengquan** [comment]
Some data files have been intentionally removed due to confidentiality agreements in corporation with other institutes. 

However, 'price.mat' can be extracted and simulated from EMCSG official website here: 
https://www.emcsg.com/MarketData/PriceInformation

As the prices used in the manuscript were USEP, you may add upper/lower buffers to simulate buying/selling prices.
