### ISSUE TITLE
Dear author, is there any plotting file of your simulation results? I will be very appreciate if you can offer that!

### ISSUE THREAD

**Issue by 2226123114** [blackmount8/Generalized_MG#3]

**Comment by juchengquan** [comment]
Hi, 

You may refer to this manuscript published here. Note that please do follow the citation formation if it is being used in your research. 

_C. Ju, "Hierarchically Coordinated Energy Management for A Regional Multi-microgrid Community", arXiv: https://arxiv.org/abs/2102.03745, doi: 10.48550/ARXIV.2102.03745._

As the diagrams were plotted in OriginPro, however, it was not included in this repository due to other data-related reasons. Nevertheless, it is suggested that you may use your simulation result to produce the plotting files under discretion. 

Thanks.
